var q= require("q");
var express = require('express');
var mongoose=require('mongoose');
mongoose.Promise = global.Promise;
var sim=mongoose.Schema({
    sim1: {type: String},
    sim2: {type: String},
    gia: {type: Number},
    dau2: {type: String},
    dau3: {type: String},
    dau4: {type: String},
    dau5: {type: String},
    dau6: {type: String},
    dau7: {type: String},
    dau8: {type: String},
    dau9: {type: String},
    duoi2: {type: String},
    duoi3: {type: String},
    duoi4: {type: String},
    duoi5: {type: String},
    duoi6: {type: String},
    duoi7: {type: String},
    duoi8: {type: String},
    duoi9: {type: String},
    daily: {type: String},
    tendaily: {type: String},
    stt_daily: {type: String},
    loaisim: {type: String},
    mang: {type: String},
    lucquy: {type: Number},
    nguquy: {type: Number},
    tuquy: {type: Number},
    tamhoa: {type: Number},
    tamhoakep: {type: Number},
    sanhtien:{type: Number},
    simlap: {type: Number},
    simtaxi: {type: Number},
    simkep: {type: Number},
    nguquygiua: {type: Number},
    tuquygiua: {type: Number},
    locphat: {type: Number},
    sinhtailocphat:{type: Number},
    phattai: {type: Number},
    thantai: {type: Number},
    ongdia: {type: Number},
    ganhdao: {type: Number},
    soiguong: {type: Number},
    namsinh: {type: Number},
    simganh: {type: Number},
    sanbang: {type: Number},
    bonmua: {type: Number},
    docnhat: {type: Number},
    stt: {type: Number},
    file: {type: String},
    ngaytao: {type: Number},
    hienthi:{type: Number},
	daban:{type: Number},
    v90:{type: Number},
}, {collection : 'table_sim'});
module.exports = mongoose.model('sim', sim);
